 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace S2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID NotifyChat = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID SystemChat = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID ResponseLogin = (Nettention.Proud.RmiID)3000+3;
			public const Nettention.Proud.RmiID ResponseLogout = (Nettention.Proud.RmiID)3000+4;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			NotifyChat,
			SystemChat,
			ResponseLogin,
			ResponseLogout,
		};
	}
}

				 
